export default {
    introduction: 'Introduction',
    transaction_fees: "Account Balances and Transaction Fees",
    general_information: 'Developer Tools',
    metamask: 'Setting up MetaMask',
    faucet: 'Faucet (get tAI3 testnet tokens)',
    block_explorer: 'Block Explorer',
    remix: 'Remix Guide',
    foundry: 'Foundry Guide',
    hardhat: 'HardHat Guide',
    local: 'Local Development',
    the_graph: 'Query On-chain Data with The Graph',
    wrapping_ai3: "Wrapping AI3 on Taurus",
    NFT_guide: 'Minting and Sending NFTs',
  }
